{% set name = "python-dateutil" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/d9/77/bd458a2e387e98f71de86dcc2ca2cab64489736004c80bc12b70da8b5488/{{ name }}-{{ version }}.tar.gz
  sha256: 78e73e19c63f5b20ffa567001531680d939dc042bf7850431877645523c66709

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -v

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - python
    - six >=1.5

test:
  imports:
    - dateutil
    - dateutil.parser
    - dateutil.tz
    - dateutil.relativedelta
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dateutil/dateutil
  license: Apache-2.0 AND BSD-3-Clause
  license_file: LICENSE
  summary: Extensions to the standard Python datetime module
  doc_url: https://dateutil.readthedocs.io
  dev_url: https://github.com/dateutil/dateutil

extra:
  recipe-maintainers:
    - anaconda-packaging