{% set name = "click" %}
{% set version = "8.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/96/d3/f04c7bfcf5c1862a2a5b845c6b2b360488cf47af55dfa79c98f6a6bf98b5/{{ name }}-{{ version }}.tar.gz
  sha256: ca9853ad459e787e2192211578cc907e7594e294c7ccc834310722b41b9ca6de

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -v

requirements:
  host:
    - python
    - pip
    # build_backend_requires is null; falling back to setuptools (assumption)
    - setuptools
  run:
    - python
    - colorama  # [win]
    # importlib-metadata required only for python < 3.8; omitted as requires_python >= 3.7
    # and all supported build targets use 3.8+

test:
  imports:
    - click
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://palletsprojects.com/p/click/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Composable command line interface toolkit
  description: |
    Click is a Python package for creating beautiful command line interfaces
    in a composable way with as little code as necessary. It's the "Command
    Line Interface Creation Kit". It's highly configurable but comes with
    sensible defaults out of the box.
  doc_url: https://click.palletsprojects.com/
  dev_url: https://github.com/pallets/click

extra:
  recipe-maintainers:
    - xylar
    - ocefpaf