{% set name = "click" %}
{% set version = "8.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/72/bd/fedc277e7351917b6c4e0ac751853a97af261278a4c7808babafa8ef2120/{{ name }}-{{ version }}.tar.gz
  sha256: 48ee849951919527a045bfe3bf7baa8a959c423134e1a5b98c05c20ba75a1cbd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python >=3.7
    - pip
    # build_backend_requires is null; falling back to setuptools (assumed)
    - setuptools
  run:
    - python >=3.7
    - colorama  # [win]
    - importlib-metadata  # [py<38]

test:
  imports:
    - click
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://palletsprojects.com/p/click/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Composable command line interface toolkit
  description: |
    Click is a Python package for creating beautiful command line interfaces
    in a composable way with as little code as necessary.
  doc_url: https://click.palletsprojects.com/
  dev_url: https://github.com/pallets/click

extra:
  recipe-maintainers:
    - conda-forge/click